'use client';

import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {AlertCircle,BarChart3,ClipboardList,Database,FileClock,LayoutDashboard,LogOut,Minus,Moon,Plus,RefreshCw,Search,Settings2,Sun,Table2,Users,UserRoundCheck,WalletCards} from 'lucide-react';
import {getSupabaseBrowserClient,SUPABASE_PUBLISHABLE_KEY,SUPABASE_URL} from '../../lib/supabase-browser';

const API=`${SUPABASE_URL}/functions/v1/backoffice-section-data`;
const NAV=[
 ['Overview',[['Dashboard','/backoffice',LayoutDashboard],['Attention Queue','/backoffice/attention',AlertCircle]]],
 ['Cohort',[['Analysis','/backoffice/analysis',BarChart3],['Attendees','/backoffice/attendees',Users]]],
 ['Planning',[['MVP Demand','/backoffice/mvp-demand',ClipboardList],['Table Allocation','/backoffice/table-allocation',Table2]]],
 ['Operations',[['Volunteers','/backoffice/volunteers',UserRoundCheck],['Payments','/backoffice/payments',WalletCards]]],
 ['Configuration',[['MVP Options','/backoffice/mvp-options',Settings2],['Settings','/backoffice/settings',Settings2]]],
 ['System',[['Data Quality','/backoffice/data-quality',Database],['Audit Log','/backoffice/audit-log',FileClock]]]
];
const TITLES={attention:'Attention Queue',analysis:'Analysis',attendees:'Attendees','mvp-demand':'MVP Demand','table-allocation':'Table Allocation',volunteers:'Volunteers',payments:'Payments','mvp-options':'MVP Options',settings:'Settings','data-quality':'Data Quality','audit-log':'Audit Log'};

function agoRange(days){const d=new Date();d.setDate(d.getDate()-days+1);d.setHours(0,0,0,0);return d.getTime()}
function fmt(v){return v?new Date(v).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—'}
function money(paise){return paise?new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(paise/100):'—'}

export default function BackofficeSection({section}){
 const router=useRouter();
 const supabase=getSupabaseBrowserClient();
 const [session,setSession]=useState(null);const [profile,setProfile]=useState(null);const [data,setData]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const [theme,setTheme]=useState('light');const [scale,setScale]=useState(100);const [range,setRange]=useState('30d');const [query,setQuery]=useState('');
 const workshop='ai-lab-mumbai-2026';
 useEffect(()=>{let live=true;(async()=>{const {data:s}=await supabase.auth.getSession();if(!live)return;if(!s.session){router.replace('/backoffice/login');return}const {data:a}=await supabase.from('backoffice_users').select('email,role,is_active').eq('user_id',s.session.user.id).maybeSingle();if(!a?.is_active){await supabase.auth.signOut();router.replace('/backoffice/login');return}setSession(s.session);setProfile(a)})();return()=>{live=false}},[router,supabase]);
 async function load(){if(!session)return;setLoading(true);setError('');try{const r=await fetch(`${API}?workshop_key=${encodeURIComponent(workshop)}`,{headers:{Authorization:`Bearer ${session.access_token}`,apikey:SUPABASE_PUBLISHABLE_KEY}});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not load data');setData(j)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[session]);
 const attendees=useMemo(()=>{let rows=data?.attendees||[];if(range!=='all'){const cutoff=agoRange(range==='7d'?7:30);rows=rows.filter(x=>new Date(x.submitted_at||0).getTime()>=cutoff)}const q=query.trim().toLowerCase();if(q)rows=rows.filter(x=>[x.full_name,x.email,x.phone,x.company_organisation,x.city,x.industry,x.functional_area].some(v=>String(v||'').toLowerCase().includes(q)));return rows},[data,range,query]);
 const title=TITLES[section]||'Back Office';
 const paid=attendees.filter(x=>x.payment_status==='paid');
 const demand=useMemo(()=>{const w1=Number(data?.settings?.mvp_first_choice_weight||2),w2=Number(data?.settings?.mvp_second_choice_weight||1);const m=new Map();attendees.forEach(a=>(a.mvp_preferences||[]).forEach(p=>{const x=m.get(p.title)||{title:p.title,first:0,second:0};p.rank===1?x.first++:x.second++;m.set(p.title,x)}));return [...m.values()].map(x=>({...x,score:x.first*w1+x.second*w2})).sort((a,b)=>b.score-a.score)},[attendees,data]);
 async function signOut(){await supabase.auth.signOut();router.replace('/backoffice/login')}
 if(!session)return <main className="boBoot">Checking administrator access…</main>;
 return <main className="boV2 boSectionApp" data-theme={theme} style={{'--bo-scale':scale/100}}>
  <aside className="boSidebar"><div className="boBrand"><img src="https://zvmmgkspdgbfcqmnizga.supabase.co/storage/v1/object/public/ai-lab-ui/logo/AI_LAB_primary_logo_transparent.png" alt="AI Lab"/><span>Back Office</span></div><nav>{NAV.map(([group,items])=><div className="boNavGroup" key={group}><b>{group}</b>{items.map(([label,href,Icon])=><a className={`boNavItem ${href.endsWith(section)?'active':''}`} href={href} key={label}><Icon size={16}/><span>{label}</span></a>)}</div>)}</nav><div className="boAdmin"><span>{profile?.email}</span><small>{(profile?.role||'super_admin').replaceAll('_',' ')}</small><button onClick={signOut}><LogOut size={14}/> Sign out</button></div></aside>
  <section className="boCanvas">
   <div className="boUniversalBar"><label className="boCohortControl"><span>Cohort</span><select value={workshop} readOnly><option>AI Lab Mumbai 2026</option></select></label><div className="boGlobalSearch"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search people…"/></div><div className="boUniversalRight"><div className="boDateFilter">{[['7D','7d'],['30D','30d'],['All','all']].map(([l,v])=><button className={range===v?'on':''} onClick={()=>setRange(v)} key={v}>{l}</button>)}</div><div className="boTextScaleInline"><button onClick={()=>setScale(Math.max(100,scale-25))}><Minus size={12}/></button><span>{scale}%</span><button onClick={()=>setScale(Math.min(200,scale+25))}><Plus size={12}/></button></div><button className="boIconControl" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={15}/>:<Moon size={15}/>}</button><button className={`boIconControl ${loading?'spinning':''}`} onClick={load}><RefreshCw size={15}/></button><div className="boProfileControl"><span>{(profile?.email||'A')[0].toUpperCase()}</span></div></div></div>
   <header className="boTopbar"><div><span>{section==='analysis'?'COHORT':'BACK OFFICE'}</span><h1>{title}</h1><p>{subtitle(section)}</p></div></header>
   <div className="boScope"><span>AI Lab Mumbai 2026 · {range==='all'?'All time':range==='7d'?'Last 7 days':'Last 30 days'}</span><small>{data?.last_updated?`Updated ${new Date(data.last_updated).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}`:''}</small></div>
   {error&&<div className="boError">{error}<button onClick={load}>Retry</button></div>}
   {renderSection(section,{attendees,paid,demand,data,loading,money,fmt})}
  </section>
 </main>
}

function subtitle(section){return ({attention:'Exceptions and operational items requiring action.',analysis:'Deterministic cohort analysis calculated from registration data.',attendees:'Search, review and manage attendee records.',payments:'Payment status and reconciliation view.','mvp-demand':'Preference demand calculated from first and second choices.','table-allocation':'Allocation status, rules and explainability before publishing.',volunteers:'Volunteer staffing status for workshop tables.','mvp-options':'Manage the MVP choices offered to applicants.',settings:'Workshop and allocation rules used by the planning engine.','data-quality':'Deterministic checks for incomplete or inconsistent records.','audit-log':'Administrative changes and system actions.'}[section]||'Workshop operations.')}

function Card({title,value,meta}){return <article className="boStat"><div><span>{title}</span><strong>{value}</strong><small>{meta}</small></div></article>}
function renderSection(section,c){const {attendees,paid,demand,data,loading,fmt}=c;if(loading)return <div className="boPanel boSectionLoading">Loading…</div>;
 if(section==='attention'){const unpaid=attendees.filter(x=>x.payment_status!=='paid');const unallocated=paid.filter(x=>!x.table);return <><div className="boStats boStats3"><Card title="Unpaid / Pending" value={unpaid.length} meta="requires follow-up"/><Card title="Paid but unallocated" value={unallocated.length} meta="allocation required"/><Card title="Data issues" value={(data?.data_quality?.missing_company||0)+(data?.data_quality?.missing_function||0)} meta="profile completeness"/></div><div className="boPanel boSimpleList">{unallocated.map(a=><div key={a.id}><b>{a.full_name}</b><span>Paid · no table assigned</span></div>)}{!unallocated.length&&<p>No allocation exceptions in this scope.</p>}</div></>}
 if(section==='analysis'){const group=(key)=>{const m=new Map();attendees.forEach(a=>m.set(a[key]||'Not specified',(m.get(a[key]||'Not specified')||0)+1));return [...m.entries()].sort((a,b)=>b[1]-a[1])};return <div className="boAnalysisGrid"><Breakdown title="AI readiness" rows={group('ai_experience_level')} total={attendees.length}/><Breakdown title="Industry" rows={group('industry')} total={attendees.length}/><Breakdown title="Function" rows={group('functional_area')} total={attendees.length}/><Breakdown title="Experience" rows={group('years_experience')} total={attendees.length}/></div>}
 if(section==='attendees')return <DataTable rows={attendees} cols={[['full_name','Name'],['company_organisation','Company'],['career_role','Role'],['ai_experience_level','AI Level'],['payment_status','Payment'],['table','Table']]}/>;
 if(section==='mvp-demand')return <div className="boPanel"><div className="boRuleNote"><b>Weighting rule</b><span>Preference 1 = {data?.settings?.mvp_first_choice_weight||2} points. Preference 2 = {data?.settings?.mvp_second_choice_weight||1} point. Weighted score = P1×weight + P2×weight.</span></div><table className="boDataTable"><thead><tr><th>MVP</th><th>P1</th><th>P2</th><th>Weighted score</th></tr></thead><tbody>{demand.map(x=><tr key={x.title}><td>{x.title}</td><td>{x.first}</td><td>{x.second}</td><td><b>{x.score}</b></td></tr>)}</tbody></table></div>;
 if(section==='table-allocation'){const tables=data?.tables||[];return <><div className="boPanel boRuleNote"><b>Allocation order</b><span>1. Maximise MVP preference fit. 2. Balance AI readiness. 3. Improve functional and experience diversity. 4. Respect table capacity and locked/manual decisions. Every automated assignment must expose its reason and score.</span></div><div className="boTableCards">{tables.length?tables.map(t=><article className="boPanel" key={t.id}><span>TABLE {t.table_number}</span><h3>{t.label||t.mvp_options?.title||'Unlabelled table'}</h3><p>Status: {t.status}</p></article>):<div className="boPanel"><h3>No allocation run yet</h3><p>The rules are available. A draft allocation has not been generated yet.</p></div>}</div></>}
 if(section==='volunteers')return <div className="boPanel boEmptyModule"><h2>Volunteer allocation is intentionally waiting for volunteer intake.</h2><p>The attendee-side requirement is already calculated: <b>{Math.ceil(paid.length/Number(data?.settings?.max_attendees_per_table||5))*Number(data?.settings?.volunteers_per_table||1)}</b> volunteers required at the current table rules. Once the volunteer module captures availability and skills, assignments can be automated against table needs.</p></div>;
 if(section==='payments')return <DataTable rows={attendees} cols={[['full_name','Attendee'],['email','Email'],['payment_status','Status'],['payment_reference','Reference'],['paid_at','Paid on']]}/>;
 if(section==='mvp-options')return <div className="boPanel boSimpleList">{(data?.mvp_options||[]).map(x=><div key={x.id}><b>{x.title}</b><span>{x.is_active?'Active':'Inactive'} · {x.description||'No description'}</span></div>)}</div>;
 if(section==='settings'){const s=data?.settings||{};return <div className="boSettingsGrid"><Setting label="Attendees / table" value={s.max_attendees_per_table}/><Setting label="Volunteers / table" value={s.volunteers_per_table}/><Setting label="Preference 1 weight" value={s.mvp_first_choice_weight}/><Setting label="Preference 2 weight" value={s.mvp_second_choice_weight}/><Setting label="AI balance" value={s.use_ai_balance?'On':'Off'}/><Setting label="Functional diversity" value={s.use_functional_diversity?'On':'Off'}/><Setting label="Experience diversity" value={s.use_experience_diversity?'On':'Off'}/></div>}
 if(section==='data-quality'){const q=data?.data_quality||{};return <div className="boStats boStats4"><Card title="Missing company" value={q.missing_company||0} meta="profile field"/><Card title="Missing function" value={q.missing_function||0} meta="profile field"/><Card title="Unpaid" value={q.unpaid||0} meta="payment state"/><Card title="Paid unallocated" value={q.unallocated_paid||0} meta="planning state"/></div>}
 if(section==='audit-log')return <div className="boPanel"><table className="boDataTable"><thead><tr><th>Time</th><th>Action</th><th>Entity</th><th>Details</th></tr></thead><tbody>{(data?.audit||[]).map(x=><tr key={x.id}><td>{fmt(x.created_at)}</td><td>{x.action}</td><td>{x.entity_type}</td><td>{JSON.stringify(x.details||{})}</td></tr>)}</tbody></table>{!(data?.audit||[]).length&&<p>No audit events recorded yet.</p>}</div>;
 return <div className="boPanel">Unknown section.</div>}
function DataTable({rows,cols}){return <div className="boPanel boTableWrap"><table className="boDataTable"><thead><tr>{cols.map(c=><th key={c[0]}>{c[1]}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}>{cols.map(([k])=><td key={k}>{k==='table'?(r.table?`Table ${r.table.table_number}`:'Unassigned'):k==='paid_at'?fmt(r[k]):String(r[k]??'—')}</td>)}</tr>)}</tbody></table>{!rows.length&&<p>No records match the current filters.</p>}</div>}
function Breakdown({title,rows,total}){return <article className="boPanel"><h2>{title}</h2><div className="boBreakdown">{rows.slice(0,8).map(([label,count])=><div key={label}><span>{label}<b>{count}</b></span><i><em style={{width:`${total?Math.round(count/total*100):0}%`}}/></i></div>)}</div></article>}
function Setting({label,value}){return <article className="boPanel boSetting"><span>{label}</span><strong>{String(value??'—')}</strong></article>}
