'use client';
import Image from 'next/image';
import Link from 'next/link';
import {useEffect,useMemo,useRef,useState} from 'react';
import * as RadioGroup from '@radix-ui/react-radio-group';
import * as Checkbox from '@radix-ui/react-checkbox';
import * as Progress from '@radix-ui/react-progress';
import {ArrowLeft,ArrowRight,Check,CheckCircle2,Cloud,Eye,Network,Sparkles,Users,Upload,UserRound} from 'lucide-react';
import {getSupabaseBrowserClient} from '../../../lib/supabase-browser';
import './apply.css';

const steps=['You','Profile','Stack','Experience','Your Work','Commitment','Submit'];
const defaultTools=[['claude','Claude / Claude Code','/images/volunteer/stack-claude.webp'],['codex','OpenAI Codex','/images/volunteer/stack-openai.webp'],['github','GitHub','/images/volunteer/stack-github.webp'],['vercel','Vercel','/images/volunteer/stack-vercel.webp'],['supabase','Supabase','/images/volunteer/stack-supabase.webp']];
const levels=['New to it','Used it','Comfortable','Built with it'];
const exp=['Worked with a GitHub repository','Deployed an application','Created or used a database','Implemented authentication','Worked with APIs','Configured environment variables','Debugged a broken application'];
const commitments=['I am available for both workshop days','I am available for the full workshop hours','I will bring my own laptop and charger','I am comfortable troubleshooting with participants','I am comfortable supporting a group rather than only observing','I understand this is an active volunteer role'];
const initial={name:'',email:'',phone:'',city:'',organisation:'',role:'',linkedin:'',github:'',background:'',interest:'',preferredRole:'',why:'',useful:'',stack:{},experience:[],strongest:'',contribution:'',projectUrl:'',repoUrl:'',otherUrl:'',commitment:[],accurate:false,consent:false,photoApproved:false};

function Field({label,children,hint}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
function CheckRow({checked,onCheckedChange,label}){return <label className="checkRow"><Checkbox.Root className="checkRoot" checked={checked} onCheckedChange={onCheckedChange}><Checkbox.Indicator><Check/></Checkbox.Indicator></Checkbox.Root><span>{label}</span></label>}
function emailOk(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v.trim())}
function urlOk(v){if(!v.trim())return true;try{const u=new URL(v);return u.protocol==='http:'||u.protocol==='https:'}catch{return false}}
function phoneOk(v){return v.replace(/\D/g,'').length>=8}
function token(){const a=new Uint8Array(32);crypto.getRandomValues(a);return Array.from(a,x=>x.toString(16).padStart(2,'0')).join('')}
let moderationModels;
async function moderatePhoto(canvas){
 if(!moderationModels){
  const [tf,nsfw,blazeface]=await Promise.all([import('@tensorflow/tfjs'),import('nsfwjs'),import('@tensorflow-models/blazeface')]);
  tf.enableProdMode();await tf.ready();
  moderationModels=Promise.all([nsfw.load('MobileNetV2'),blazeface.load()]);
 }
 const [nsfwModel,faceModel]=await moderationModels;
 const [predictions,faces]=await Promise.all([nsfwModel.classify(canvas,5),faceModel.estimateFaces(canvas,false)]);
 const scores=Object.fromEntries(predictions.map(x=>[x.className,Number(x.probability.toFixed(4))]));
 if((scores.Porn||0)>=.35||(scores.Hentai||0)>=.35||(scores.Sexy||0)>=.55) return {ok:false,error:'This image is not permitted. Please upload an appropriate profile photo.',scores,faces:faces.length};
 const confident=faces.filter(x=>!x.probability||x.probability[0]>=.85);
 if(confident.length===0)return {ok:false,error:"We couldn't detect a clear face. Please upload a recent, front-facing photo of yourself.",scores,faces:0};
 if(confident.length>1)return {ok:false,error:'Only one person is allowed in the photo. Please upload a photo of yourself only.',scores,faces:confident.length};
 return {ok:true,scores,faces:1};
}

export default function VolunteerApply(){
 const[step,setStep]=useState(0),[data,setData]=useState(initial),[activeTools,setActiveTools]=useState(defaultTools),[activeLevels,setActiveLevels]=useState(levels),[saved,setSaved]=useState('Saved on this device'),[submitted,setSubmitted]=useState(false),[appId,setAppId]=useState(null),[resumeToken,setResumeToken]=useState(null),[photoPreview,setPhotoPreview]=useState(''),[photoError,setPhotoError]=useState(''),[photoBusy,setPhotoBusy]=useState(false),[submitError,setSubmitError]=useState('');const hydrated=useRef(false);
 useEffect(()=>{(async()=>{try{const{data:f}=await getSupabaseBrowserClient().from('volunteer_form_versions').select('form_config').eq('workshop_key','ai-lab-mumbai-2026').eq('status','published').order('version',{ascending:false}).limit(1).maybeSingle();if(f?.form_config){const names=f.form_config.stack_tools||[];const known=Object.fromEntries(defaultTools.map(t=>[t[1],t]));setActiveTools(names.map((name,i)=>known[name]||['tool_'+i,name,null]));if(f.form_config.proficiency_levels?.length)setActiveLevels(f.form_config.proficiency_levels)}}catch{}})();},[]);
 useEffect(()=>{try{const v=localStorage.getItem('ai-lab-volunteer-draft-v2'),id=localStorage.getItem('ai-lab-volunteer-id'),rt=localStorage.getItem('ai-lab-volunteer-token');if(v)setData({...initial,...JSON.parse(v)});if(id)setAppId(id);if(rt)setResumeToken(rt)}catch{}hydrated.current=true},[]);
 useEffect(()=>{if(!hydrated.current)return;const t=setTimeout(async()=>{try{localStorage.setItem('ai-lab-volunteer-draft-v2',JSON.stringify(data));if(appId&&resumeToken){setSaved('Saving…');const{error}=await getSupabaseBrowserClient().rpc('save_volunteer_application',{p_id:appId,p_token:resumeToken,p_payload:{...data,currentStep:step+1},p_step:step+1});setSaved(error?'Saved on this device':'Auto-saved just now')}else setSaved('Saved on this device')}catch{setSaved('Saved on this device')}},650);return()=>clearTimeout(t)},[data,step,appId,resumeToken]);
 const set=(k,v)=>setData(d=>({...d,[k]:v}));const toggle=(k,v)=>setData(d=>({...d,[k]:d[k].includes(v)?d[k].filter(x=>x!==v):[...d[k],v]}));
 const valid=useMemo(()=>[!!(data.name.trim()&&emailOk(data.email)&&phoneOk(data.phone)&&data.city.trim()&&data.organisation.trim()&&data.role&&urlOk(data.linkedin)&&urlOk(data.github)&&data.photoApproved),!!(data.background&&data.interest&&data.preferredRole&&data.why&&data.useful),activeTools.every(t=>data.stack[t[0]]),true,!!(data.strongest.trim().length>=10&&data.contribution.trim().length>=10&&urlOk(data.projectUrl)&&urlOk(data.repoUrl)&&urlOk(data.otherUrl)),commitments.every(x=>data.commitment.includes(x)),data.accurate&&data.consent][step],[data,step,activeTools]);
 async function ensureApplication(payload=data){if(appId&&resumeToken)return{appId,resumeToken};const rt=token();const{data:r,error}=await getSupabaseBrowserClient().rpc('start_volunteer_application',{p_payload:{...payload,currentStep:step+1},p_token:rt});if(error)throw error;setAppId(r.id);setResumeToken(rt);localStorage.setItem('ai-lab-volunteer-id',r.id);localStorage.setItem('ai-lab-volunteer-token',rt);return{appId:r.id,resumeToken:rt}}
 async function photoChange(e){const file=e.target.files?.[0];setPhotoError('');if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setPhotoError('Please upload a JPG, PNG or WebP image.');return}if(file.size>5*1024*1024){setPhotoError('Maximum upload size is 5 MB.');return}setPhotoBusy(true);try{const bitmap=await createImageBitmap(file);if(bitmap.width<240||bitmap.height<240)throw new Error('Please upload a clear photo at least 240 × 240 pixels.');const size=800,scale=Math.min(size/bitmap.width,size/bitmap.height,1),w=Math.round(bitmap.width*scale),h=Math.round(bitmap.height*scale),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(bitmap,0,0,w,h);const moderation=await moderatePhoto(canvas);if(!moderation.ok)throw new Error(moderation.error);const blob=await new Promise(r=>canvas.toBlob(r,'image/webp',.82));if(!blob)throw new Error('We could not process this image. Please try another photo.');const ids=await ensureApplication();const path='pending/'+ids.appId+'.webp';const sb=getSupabaseBrowserClient();const{error:up}=await sb.storage.from('volunteer-photos').upload(path,blob,{contentType:'image/webp',upsert:true});if(up)throw up;const{error:ap}=await sb.rpc('approve_volunteer_photo',{p_id:ids.appId,p_token:ids.resumeToken,p_path:path,p_moderation:{clientSanitized:true,model:'nsfwjs+blazeface',scores:moderation.scores,faces:moderation.faces}});if(ap)throw ap;setPhotoPreview(URL.createObjectURL(blob));set('photoApproved',true)}catch(err){setPhotoError(err?.message||'Photo upload failed. Please try again.');set('photoApproved',false)}finally{setPhotoBusy(false);e.target.value=''}}
 const next=()=>valid&&setStep(s=>Math.min(6,s+1)),back=()=>setStep(s=>Math.max(0,s-1));
 async function submit(){if(!valid)return;setSubmitError('');try{const ids=await ensureApplication();const{error}=await getSupabaseBrowserClient().rpc('submit_volunteer_application',{p_id:ids.appId,p_token:ids.resumeToken,p_payload:data});if(error)throw error;['ai-lab-volunteer-draft-v2','ai-lab-volunteer-id','ai-lab-volunteer-token'].forEach(k=>localStorage.removeItem(k));setSubmitted(true)}catch(e){setSubmitError(e?.message||'We could not submit your application. Please try again.')}}
 if(submitted)return <main className="applyShell"><aside className="applyRail"><Brand/><RailBenefits/></aside><section className="complete"><CheckCircle2/><span>APPLICATION RECEIVED</span><h1>Thank you for applying.</h1><p>Your application is now with the AI Lab team.</p><div><strong>What happens next?</strong><p>We’ll review your experience, work and availability. If your profile matches what we need, we’ll contact you on the email or WhatsApp number you provided. Please don’t submit another application.</p></div><Link href="/">Back to AI Lab</Link></section></main>;
 return <main className="applyShell"><aside className="applyRail"><Brand/><h1>Volunteer at<br/><strong>AI Lab</strong></h1><p>Build AI MVPs. Impact real businesses. Grow together.</p><RailBenefits/><div className="dates"><b>Workshop Dates</b><span>25 Sep (Thu) & 26 Sep (Fri) 2026</span><span>Full Day | Mumbai</span></div></aside><section className="formPane">
 <Progress.Root className="mobileProgress" value={(step+1)/7*100}><Progress.Indicator style={{transform:`translateX(-${100-(step+1)/7*100}%)`}}/></Progress.Root>
 <nav className="stepper" aria-label="Application progress">{steps.map((s,i)=><button key={s} type="button" className={i===step?'active':i<step?'done':''} onClick={()=>i<step&&setStep(i)} aria-current={i===step?'step':undefined}><i>{i<step?<Check/>:i+1}</i><span>{s}</span></button>)}</nav>
 <header className="formHead"><small>Step {step+1} of 7</small><h1>{['Tell us about you.','Your profile.','What’s in your stack?','What have you actually done?','Show us your work.','Can we count on you?','Review & submit.'][step]}</h1><p>{['Start with the basics.','Help us understand your background and where you can contribute.','Rate your experience with the tools we work with.','Select the things you have personally worked on.','Evidence beats claims. Share what you have built.','Volunteering here means actively helping teams build.','Check your application before sending it.'][step]}</p></header>
 <div className="formBody">{step===0&&<><div className="photoBlock"><div className="photoPreview">{photoPreview?<img src={photoPreview} alt="Your selected profile preview"/>:<UserRound/>}</div><div><b>Your photo *</b><p>Upload a recent, clear photo of yourself. Only you should appear in the image.</p><label className="uploadButton"><Upload/> {photoBusy?'Checking face & image…':data.photoApproved?'Change photo':'Upload photo'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={photoChange} disabled={photoBusy}/></label><small>JPG, PNG or WebP · max 5 MB. No objects, group photos, screenshots, nudity, sexual/obscene or inappropriate imagery. You are responsible for uploading an appropriate image you have the right to use.</small>{photoError&&<strong className="photoError" role="alert">{photoError}</strong>}{data.photoApproved&&<strong className="photoOk"><Check/> Photo accepted</strong>}</div></div><div className="fieldGrid"><Field label="Full name"><input value={data.name} onChange={e=>set('name',e.target.value)} autoComplete="name"/></Field><Field label="Email address"><input type="email" value={data.email} onChange={e=>set('email',e.target.value)} autoComplete="email" aria-invalid={!!data.email&&!emailOk(data.email)}/>{data.email&&!emailOk(data.email)&&<small className="fieldError">Enter a valid email address.</small>}</Field><Field label="Phone / WhatsApp"><input value={data.phone} onChange={e=>set('phone',e.target.value)} autoComplete="tel" aria-invalid={!!data.phone&&!phoneOk(data.phone)}/>{data.phone&&!phoneOk(data.phone)&&<small className="fieldError">Enter a valid phone / WhatsApp number.</small>}</Field><Field label="City"><input value={data.city} onChange={e=>set('city',e.target.value)}/></Field><Field label="College / University / Company"><input value={data.organisation} onChange={e=>set('organisation',e.target.value)}/></Field><Field label="Current role"><select value={data.role} onChange={e=>set('role',e.target.value)}><option value="">Select role</option>{['Student','Working Professional','Founder','Developer','Designer','AI Enthusiast','Other'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="LinkedIn profile" hint="Optional"><input type="url" value={data.linkedin} onChange={e=>set('linkedin',e.target.value)}/>{data.linkedin&&!urlOk(data.linkedin)&&<small className="fieldError">Enter a complete URL beginning with http:// or https://.</small>}</Field><Field label="GitHub profile" hint="Recommended for technical roles"><input type="url" value={data.github} onChange={e=>set('github',e.target.value)}/>{data.github&&!urlOk(data.github)&&<small className="fieldError">Enter a complete URL beginning with http:// or https://.</small>}</Field></div></>}
 {step===1&&<div className="stacked"><Field label="Education / work background"><textarea value={data.background} onChange={e=>set('background',e.target.value)}/></Field><div className="fieldGrid"><Field label="Primary area of interest"><input value={data.interest} onChange={e=>set('interest',e.target.value)}/></Field><Field label="Preferred volunteer role"><input value={data.preferredRole} onChange={e=>set('preferredRole',e.target.value)}/></Field></div><Field label="Why do you want to volunteer at AI Lab?"><textarea value={data.why} onChange={e=>set('why',e.target.value)}/></Field><Field label="What would make you useful to a participant or team?"><textarea value={data.useful} onChange={e=>set('useful',e.target.value)}/></Field></div>}
 {step===2&&<div className="stackCard">{activeTools.map(t=><div className="toolRow" key={t[0]}><div className="toolName">{t[2]&&<Image src={t[2]} alt="" width={54} height={54}/>}<b>{t[1]}</b></div><RadioGroup.Root className="levelGroup" value={data.stack[t[0]]||''} onValueChange={v=>setData(d=>({...d,stack:{...d.stack,[t[0]]:v}}))}>{activeLevels.map(l=><label key={l} className="level"><RadioGroup.Item value={l}><RadioGroup.Indicator/></RadioGroup.Item><span>{l}</span></label>)}</RadioGroup.Root></div>)}</div>}
 {step===3&&<div className="checkList">{exp.map(x=><CheckRow key={x} label={x} checked={data.experience.includes(x)} onCheckedChange={()=>toggle('experience',x)}/>)}</div>}
 {step===4&&<div className="stacked"><Field label="Strongest project / work"><textarea value={data.strongest} onChange={e=>set('strongest',e.target.value)}/></Field><Field label="What did you personally contribute?"><textarea value={data.contribution} onChange={e=>set('contribution',e.target.value)}/></Field><div className="fieldGrid"><Field label="Project / demo URL"><input type="url" value={data.projectUrl} onChange={e=>set('projectUrl',e.target.value)}/></Field><Field label="Repository URL"><input type="url" value={data.repoUrl} onChange={e=>set('repoUrl',e.target.value)}/></Field></div><Field label="Additional work URL"><input type="url" value={data.otherUrl} onChange={e=>set('otherUrl',e.target.value)}/></Field></div>}
 {step===5&&<div className="checkList">{commitments.map(x=><CheckRow key={x} label={x} checked={data.commitment.includes(x)} onCheckedChange={()=>toggle('commitment',x)}/>)}</div>}
 {step===6&&<div className="review"><div className="reviewGrid"><section><small>YOU</small><b>{data.name}</b><span>{data.email}</span><span>{data.phone} · {data.city}</span></section><section><small>PROFILE</small><b>{data.role}</b><span>{data.organisation}</span><span>{data.preferredRole}</span></section><section><small>STACK</small>{activeTools.map(t=><span key={t[0]}>{t[1]}: <b>{data.stack[t[0]]}</b></span>)}</section><section><small>EXPERIENCE</small><b>{data.experience.length} practical areas selected</b><span>{data.strongest}</span></section></div><CheckRow label="I confirm the information in this application is accurate." checked={data.accurate} onCheckedChange={v=>set('accurate',v===true)}/><CheckRow label="I consent to AI Lab using this information and my photo for volunteer selection and workshop coordination." checked={data.consent} onCheckedChange={v=>set('consent',v===true)}/>{submitError&&<p className="submitError" role="alert">{submitError}</p>}</div>}</div>
 <div className="formActions"><button type="button" className="back" onClick={back} disabled={step===0}><ArrowLeft/> Back</button><div className="tip"><Sparkles/><span><b>Tip</b> Be honest — this helps us create the right experience for you.</span></div>{step<6?<button type="button" className="next" disabled={!valid} onClick={next}>Continue <ArrowRight/></button>:<button type="button" className="next" disabled={!valid} onClick={submit}>Submit application <ArrowRight/></button>}</div>
 <footer className="saveBar"><span><Cloud/> {saved}</span><span>Questions? <b>volunteer@ai-lab.workshop</b></span><span>Need a break? Your progress is saved.</span></footer></section></main>
}
function Brand(){return <div className="railBrand"><span className="brandMark">A</span><div><b>AI LAB</b><small>AI BUSINESS WORKSHOP</small></div></div>}
function RailBenefits(){return <div className="railBenefits"><div><Users/><span><b>Access</b><small>Work alongside founders, CXOs and investors.</small></span></div><div><Eye/><span><b>Get Seen</b><small>Showcase your skills and build credibility.</small></span></div><div><Network/><span><b>Network</b><small>Build meaningful relationships that open doors.</small></span></div></div>}
