'use client';
import Image from 'next/image';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import * as RadioGroup from '@radix-ui/react-radio-group';
import * as Checkbox from '@radix-ui/react-checkbox';
import * as Progress from '@radix-ui/react-progress';
import {ArrowLeft,ArrowRight,Check,CheckCircle2,Cloud,Eye,Network,ShieldCheck,Sparkles,Users} from 'lucide-react';
import './apply.css';

const steps=['You','Profile','Stack','Experience','Your Work','Commitment','Submit'];
const tools=[
 ['claude','Claude / Claude Code','/images/volunteer/stack-claude.webp'],
 ['codex','OpenAI Codex','/images/volunteer/stack-openai.webp'],
 ['github','GitHub','/images/volunteer/stack-github.webp'],
 ['vercel','Vercel','/images/volunteer/stack-vercel.webp'],
 ['supabase','Supabase','/images/volunteer/stack-supabase.webp']
];
const levels=['New to it','Used it','Comfortable','Built with it'];
const exp=['Worked with a GitHub repository','Deployed an application','Created or used a database','Implemented authentication','Worked with APIs','Configured environment variables','Debugged a broken application'];
const commitments=['I am available for both workshop days','I am available for the full workshop hours','I will bring my own laptop and charger','I am comfortable troubleshooting with participants','I am comfortable supporting a group rather than only observing','I understand this is an active volunteer role'];
const initial={name:'',email:'',phone:'',city:'',organisation:'',role:'',background:'',interest:'',preferredRole:'',why:'',useful:'',stack:{},experience:[],strongest:'',contribution:'',projectUrl:'',repoUrl:'',otherUrl:'',commitment:[],accurate:false,consent:false};

function Field({label,children,hint}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
function CheckRow({checked,onCheckedChange,label}){return <label className="checkRow"><Checkbox.Root className="checkRoot" checked={checked} onCheckedChange={onCheckedChange}><Checkbox.Indicator><Check/></Checkbox.Indicator></Checkbox.Root><span>{label}</span></label>}

export default function VolunteerApply(){
 const[step,setStep]=useState(0);const[data,setData]=useState(initial);const[saved,setSaved]=useState('Saving…');const[submitted,setSubmitted]=useState(false);
 useEffect(()=>{try{const v=localStorage.getItem('ai-lab-volunteer-draft-v1');if(v)setData({...initial,...JSON.parse(v)})}catch{}},[]);
 useEffect(()=>{const t=setTimeout(()=>{try{localStorage.setItem('ai-lab-volunteer-draft-v1',JSON.stringify(data));setSaved('Auto-saved just now')}catch{setSaved('Saved in this session')}},450);return()=>clearTimeout(t)},[data]);
 const set=(k,v)=>setData(d=>({...d,[k]:v}));const toggle=(k,v)=>setData(d=>({...d,[k]:d[k].includes(v)?d[k].filter(x=>x!==v):[...d[k],v]}));
 const valid=useMemo(()=>[!!(data.name&&data.email&&data.phone&&data.city&&data.organisation&&data.role),!!(data.background&&data.interest&&data.preferredRole&&data.why&&data.useful),tools.every(t=>data.stack[t[0]]),true,!!(data.strongest&&data.contribution),commitments.every(x=>data.commitment.includes(x)),data.accurate&&data.consent][step],[data,step]);
 const next=()=>{if(valid)setStep(s=>Math.min(6,s+1))};const back=()=>setStep(s=>Math.max(0,s-1));
 const submit=()=>{if(!valid)return;localStorage.removeItem('ai-lab-volunteer-draft-v1');setSubmitted(true)};
 if(submitted)return <main className="applyShell"><aside className="applyRail"><Brand/><RailBenefits/></aside><section className="complete"><CheckCircle2/><span>APPLICATION RECEIVED</span><h1>Thank you for applying.</h1><p>We’ve received your AI Lab volunteer application. Our team will review your experience, work and availability.</p><div><strong>What happens next?</strong><p>If your profile matches what we need for this workshop, we’ll contact you using the email or WhatsApp number you provided.</p></div><Link href="/">Back to AI Lab</Link></section></main>;
 return <main className="applyShell"><aside className="applyRail"><Brand/><h1>Volunteer at<br/><strong>AI Lab</strong></h1><p>Build AI MVPs. Impact real businesses. Grow together.</p><RailBenefits/><div className="dates"><b>Workshop Dates</b><span>25 Sep (Thu) & 26 Sep (Fri) 2026</span><span>Full Day | Mumbai</span></div></aside>
 <section className="formPane">
  <Progress.Root className="mobileProgress" value={(step+1)/7*100}><Progress.Indicator style={{transform:`translateX(-${100-(step+1)/7*100}%)`}}/></Progress.Root>
  <nav className="stepper" aria-label="Application progress">{steps.map((s,i)=><button key={s} type="button" className={i===step?'active':i<step?'done':''} onClick={()=>i<step&&setStep(i)} aria-current={i===step?'step':undefined}><i>{i<step?<Check/>:i+1}</i><span>{s}</span></button>)}</nav>
  <header className="formHead"><small>Step {step+1} of 7</small><h1>{['Tell us about you.','Your profile.','What’s in your stack?','What have you actually done?','Show us your work.','Can we count on you?','Review & submit.'][step]}</h1><p>{['Start with the basics.','Help us understand your background and where you can contribute.','Rate your experience with the tools we work with.','Select the things you have personally worked on.','Evidence beats claims. Share what you have built.','Volunteering here means actively helping teams build.','Check your application before sending it.'][step]}</p></header>
  <div className="formBody">{step===0&&<div className="fieldGrid"><Field label="Full name"><input value={data.name} onChange={e=>set('name',e.target.value)} autoComplete="name"/></Field><Field label="Email address"><input type="email" value={data.email} onChange={e=>set('email',e.target.value)} autoComplete="email"/></Field><Field label="Phone / WhatsApp"><input value={data.phone} onChange={e=>set('phone',e.target.value)} autoComplete="tel"/></Field><Field label="City"><input value={data.city} onChange={e=>set('city',e.target.value)} autoComplete="address-level2"/></Field><Field label="College / University / Company"><input value={data.organisation} onChange={e=>set('organisation',e.target.value)}/></Field><Field label="Current role"><select value={data.role} onChange={e=>set('role',e.target.value)}><option value="">Select role</option>{['Student','Working Professional','Founder','Developer','Designer','AI Enthusiast','Other'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="LinkedIn profile" hint="Optional"><input type="url" value={data.linkedin||''} onChange={e=>set('linkedin',e.target.value)} placeholder="https://linkedin.com/in/..."/></Field><Field label="GitHub profile" hint="Recommended for technical roles"><input type="url" value={data.github||''} onChange={e=>set('github',e.target.value)} placeholder="https://github.com/..."/></Field></div>}
  {step===1&&<div className="stacked"><Field label="Education / work background"><textarea value={data.background} onChange={e=>set('background',e.target.value)}/></Field><div className="fieldGrid"><Field label="Primary area of interest"><input value={data.interest} onChange={e=>set('interest',e.target.value)}/></Field><Field label="Preferred volunteer role"><input value={data.preferredRole} onChange={e=>set('preferredRole',e.target.value)}/></Field></div><Field label="Why do you want to volunteer at AI Lab?"><textarea value={data.why} onChange={e=>set('why',e.target.value)}/></Field><Field label="What would make you useful to a participant or team?"><textarea value={data.useful} onChange={e=>set('useful',e.target.value)}/></Field></div>}
  {step===2&&<div className="stackCard">{tools.map(t=><div className="toolRow" key={t[0]}><div className="toolName"><Image src={t[2]} alt="" width={54} height={54}/><b>{t[1]}</b></div><RadioGroup.Root className="levelGroup" value={data.stack[t[0]]||''} onValueChange={v=>setData(d=>({...d,stack:{...d.stack,[t[0]]:v}}))}>{levels.map(l=><label key={l} className="level"><RadioGroup.Item value={l}><RadioGroup.Indicator/></RadioGroup.Item><span>{l}</span></label>)}</RadioGroup.Root></div>)}</div>}
  {step===3&&<div className="checkList">{exp.map(x=><CheckRow key={x} label={x} checked={data.experience.includes(x)} onCheckedChange={()=>toggle('experience',x)}/>)}</div>}
  {step===4&&<div className="stacked"><Field label="Strongest project / work"><textarea value={data.strongest} onChange={e=>set('strongest',e.target.value)}/></Field><Field label="What did you personally contribute?"><textarea value={data.contribution} onChange={e=>set('contribution',e.target.value)}/></Field><div className="fieldGrid"><Field label="Project / demo URL"><input type="url" value={data.projectUrl} onChange={e=>set('projectUrl',e.target.value)}/></Field><Field label="Repository URL"><input type="url" value={data.repoUrl} onChange={e=>set('repoUrl',e.target.value)}/></Field></div><Field label="Additional work URL"><input type="url" value={data.otherUrl} onChange={e=>set('otherUrl',e.target.value)}/></Field></div>}
  {step===5&&<div className="checkList">{commitments.map(x=><CheckRow key={x} label={x} checked={data.commitment.includes(x)} onCheckedChange={()=>toggle('commitment',x)}/>)}</div>}
  {step===6&&<div className="review"><div className="reviewGrid"><section><small>YOU</small><b>{data.name}</b><span>{data.email}</span><span>{data.phone} · {data.city}</span></section><section><small>PROFILE</small><b>{data.role}</b><span>{data.organisation}</span><span>{data.preferredRole}</span></section><section><small>STACK</small>{tools.map(t=><span key={t[0]}>{t[1]}: <b>{data.stack[t[0]]}</b></span>)}</section><section><small>EXPERIENCE</small><b>{data.experience.length} practical areas selected</b><span>{data.strongest}</span></section></div><CheckRow label="I confirm the information in this application is accurate." checked={data.accurate} onCheckedChange={v=>set('accurate',v===true)}/><CheckRow label="I consent to AI Lab using this information for volunteer selection and coordination." checked={data.consent} onCheckedChange={v=>set('consent',v===true)}/></div>}</div>
  <div className="formActions"><button type="button" className="back" onClick={back} disabled={step===0}><ArrowLeft/> Back</button><div className="tip"><Sparkles/><span><b>Tip</b> Be honest — this helps us create the right experience for you.</span></div>{step<6?<button type="button" className="next" disabled={!valid} onClick={next}>Continue <ArrowRight/></button>:<button type="button" className="next" disabled={!valid} onClick={submit}>Submit application <ArrowRight/></button>}</div>
  <footer className="saveBar"><span><Cloud/> {saved}</span><span>Questions? <b>volunteer@ai-lab.workshop</b></span><span>Need a break? Your progress is saved.</span></footer>
 </section></main>
}
function Brand(){return <div className="railBrand"><span className="brandMark">A</span><div><b>AI LAB</b><small>AI BUSINESS WORKSHOP</small></div></div>}
function RailBenefits(){return <div className="railBenefits"><div><Users/><span><b>Access</b><small>Work alongside founders, CXOs and investors.</small></span></div><div><Eye/><span><b>Get Seen</b><small>Showcase your skills and build credibility.</small></span></div><div><Network/><span><b>Network</b><small>Build meaningful relationships that open doors.</small></span></div></div>}
