'use client';
import Image from 'next/image';
import {useEffect,useRef,useState} from 'react';

const experts=[
['tech','TECH & AI EXPERT','AI strategy, tools & architecture'],
['legal','LEGAL EXPERT','AI governance, IP & compliance'],
['finance','FINANCE EXPERT','AI investment, ROI & scaling'],
['global','GLOBAL EXPANSION EXPERT','Go-to-market & global growth']
];
function ExpertIcon({type}){const paths={tech:<><rect x="5" y="5" width="14" height="14" rx="3"/><path d="M9 9h6v6H9zM9 2v3m6-3v3M9 19v3m6-3v3M2 9h3m-3 6h3m14-6h3m-3 6h3"/></>,legal:<><path d="M12 3v18M7 6h10M5 9l-3 6h6L5 9Zm14 0-3 6h6l-3-6ZM8 21h8"/></>,finance:<><path d="M4 19V9m6 10V5m6 14v-7m4 7V3"/><path d="m3 7 6-4 6 5 6-6"/></>,global:<><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3 4 6 4 9s-1 6-4 9c-3-3-4-6-4-9s1-6 4-9Z"/></>};return <svg className="expertIcon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">{paths[type]}</svg>}
export default function Page(){
const [menuOpen,setMenuOpen]=useState(false);const [askOpen,setAskOpen]=useState(false);const dialogRef=useRef(null);
useEffect(()=>{if(askOpen)dialogRef.current?.focus()},[askOpen]);
const closeMenu=()=>setMenuOpen(false);
return <main id="main-content">
<header><a className="brand" href="#top" aria-label="ELIV8 LYF home">ELIV<span>8</span>LYF</a><nav id="primary-nav" className={menuOpen?'open':''} aria-label="Primary navigation"><a onClick={closeMenu} href="#top">OVERVIEW</a><a onClick={closeMenu} href="#experience">EXPERIENCE</a><a onClick={closeMenu} href="#outcomes">OUTCOMES</a><a onClick={closeMenu} href="#experts">EXPERTS</a><a onClick={closeMenu} href="#sponsors">SPONSORS</a><a onClick={closeMenu} href="#faq">FAQ</a></nav><button className="menu" type="button" aria-label={menuOpen?'Close navigation menu':'Open navigation menu'} aria-expanded={menuOpen} aria-controls="primary-nav" onClick={()=>setMenuOpen(v=>!v)}>{menuOpen?'×':'☰'}</button></header>
<section id="top" className="hero" aria-labelledby="hero-title"><div className="heroCopy"><div className="topSponsor"><small>PRESENTING SPONSOR</small><strong><i aria-hidden="true">◆</i> YOUR LOGO</strong></div><h1 id="hero-title">AI <em>LAB</em></h1><h2>Stop learning about AI.<br/>Start <i>building</i> with it.</h2><p>A hands-on AI business workshop where founders, CXOs and business leaders turn real business problems into working AI solutions.</p><div className="meta"><b>MUMBAI</b><b>COMING SOON</b></div><div className="heroAction"><a href="#early">GET EARLY ACCESS <span aria-hidden="true">→</span></a><span>Join the waitlist</span></div></div><div className="videoCard"><div className="videoScene"><div className="screen" aria-hidden="true">AI LAB<small>Build. Test. Transform.</small></div><button type="button" aria-label="AI Lab workshop video coming soon" disabled>▶</button><div className="audienceSilhouette" aria-hidden="true"><i/><i/><i/><i/><i/><i/></div></div><div className="videoLabel"><small>VIDEO PREVIEW</small><b>See AI Lab in action</b></div></div></section>
<section id="experience" className="transform" aria-labelledby="experience-title"><div className="transformIntro"><h2 id="experience-title">THIS IS <em>NOT</em><br/>AN AI COURSE.</h2><span aria-hidden="true"></span><p>You don’t just watch slides.<br/>You work. You <b>build.</b><br/><strong>You do not need to be a developer.</strong></p></div><article className="problem"><div><h3>BUSINESS PROBLEM</h3><p>Siloed data</p><p>Manual work</p><p>Slow decisions</p><p>Missed opportunities</p></div><div className="personVisual"><Image src="/images/ai-lab/business-problem-mobile.jpg" alt="Professional working through operational problems before building an AI solution" width={320} height={568} sizes="(max-width: 800px) 45vw, 260px" /></div></article><div className="arrow" aria-hidden="true">→</div><article className="mvp"><div><h3>WORKING MVP</h3><p>Real solution</p><p>Measurable impact</p><p>Faster decisions</p><p>Business value</p></div><div className="laptop" role="img" aria-label="Illustration of a working AI dashboard on a laptop"><div aria-hidden="true"><b>LIVE</b><span>▥ ▥ ▥</span></div></div></article></section>
<section id="outcomes" className="lower" aria-label="People, practitioners and partners"><div className="people"><h3>AI LAB BY <em>ELIV8 LYF</em></h3><div className="portraits"><article><div className="portrait" aria-hidden="true">R</div><b>ROY</b></article><article><div className="portrait" aria-hidden="true">GT</div><b>GT</b></article></div></div><div id="experts" className="practitioners"><h3>LEARN FROM PRACTITIONERS</h3><div className="expertGrid">{experts.map(x=><article key={x[1]}><ExpertIcon type={x[0]}/><b>{x[1]}</b><p>{x[2]}</p></article>)}</div><small>Industry experts. Real-world perspectives.</small></div><div id="sponsors" className="sponsors"><h3>POWERED BY <em>PARTNERS</em> WHO BELIEVE IN BUILDING THE FUTURE</h3><div className="sponsorGrid"><article className="present"><small>PRESENTING SPONSOR</small><b>YOUR LOGO</b><p>Leading the future of<br/>AI transformation</p></article><article><small>ASSOCIATE SPONSOR</small><b>Your Logo</b><p>Empowering innovation<br/>& growth</p></article><article><small>BUSINESS MIXER SPONSOR</small><b>Your Logo</b><p>Connecting leaders.<br/>Creating opportunities.</p></article></div></div></section>
<section id="faq" className="faq" aria-labelledby="faq-title"><h2 id="faq-title">FAQ</h2><details><summary>Who should attend?</summary><p>Founders, CXOs, business owners and independent professionals who want to apply AI practically.</p></details><details><summary>Do I need to know how to code?</summary><p>No. Coding experience is not required.</p></details><details><summary>When and where?</summary><p>Mumbai. Dates will be announced soon.</p></details></section>
<section id="early" className="early" aria-labelledby="early-title"><div><b aria-hidden="true">▣</b><h2 id="early-title">AI LAB IS COMING<br/>TO MUMBAI.</h2></div><p>Be the first to know<br/>when enrolment opens.</p><form onSubmit={e=>e.preventDefault()} aria-label="AI Lab early access"><label className="srOnly" htmlFor="early-email">Email address</label><input id="early-email" name="email" autoComplete="email" required type="email" inputMode="email" placeholder="Enter your email address"/><button type="submit">GET EARLY ACCESS <span aria-hidden="true">→</span></button></form><div className="gateway" aria-hidden="true">▣</div></section>
<footer><b>ELIV<span>8</span>LYF</b><small>© 2026 ELIV8 LYF. All rights reserved.</small></footer>
<button className="ask" type="button" aria-haspopup="dialog" aria-expanded={askOpen} aria-controls="ask-dialog" onClick={()=>setAskOpen(true)}><span aria-hidden="true">●</span><b>Ask AI Lab<small>Talk to us</small></b></button>
{askOpen&&<div className="dialogBackdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setAskOpen(false)}}><section id="ask-dialog" className="askDialog" role="dialog" aria-modal="true" aria-labelledby="ask-title" tabIndex={-1} ref={dialogRef} onKeyDown={e=>{if(e.key==='Escape')setAskOpen(false)}}><button className="dialogClose" type="button" aria-label="Close Ask AI Lab" onClick={()=>setAskOpen(false)}>×</button><small>AI LAB</small><h2 id="ask-title">Ask AI Lab</h2><p>Voice and live chat will be available here soon. You can join early access now and we’ll let you know when it opens.</p><a href="#early" onClick={()=>setAskOpen(false)}>GET EARLY ACCESS →</a></section></div>}
</main>}
