'use client';
import {useEffect,useState} from 'react';
const API='https://zvmmgkspdgbfcqmnizga.supabase.co/functions/v1';
const ASSET='https://zvmmgkspdgbfcqmnizga.supabase.co/storage/v1/object/public/ai-lab-ui/';
const roles=['CXO / Executive','Founder / Co-founder','Senior Professional','Entrepreneur','Consultant','Other'];
const tools=['ChatGPT','Claude','Gemini','Copilot','Notion AI','Midjourney','DALL-E','Other'];
const levels=['Beginner','Intermediate','Advanced','Expert'];
const Icon=({children})=><span className="fieldIcon" aria-hidden="true">{children}</span>;
export default function Register(){
 const[step,setStep]=useState(1),[options,setOptions]=useState([]),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState('');
 const[f,setF]=useState({full_name:'',email:'',phone:'',city:'',age_band:'',career_role:'',company_organisation:'',industry:'',years_experience:'',functional_area:'',ai_experience_level:'',ai_tools:[],mvp_preferences:[],other_mvp_idea:'',consent:false});
 useEffect(()=>{fetch(API+'/attendee-options').then(r=>r.json()).then(x=>setOptions(x.options||[])).catch(()=>{})},[]);
 const set=(k,v)=>setF(x=>({...x,[k]:v}));const toggleTool=t=>set('ai_tools',f.ai_tools.includes(t)?f.ai_tools.filter(x=>x!==t):[...f.ai_tools,t]);const chooseMvp=slug=>{let p=f.mvp_preferences.includes(slug)?f.mvp_preferences.filter(x=>x!==slug):[...f.mvp_preferences,slug];if(p.length>2)p=p.slice(1);set('mvp_preferences',p)};
 const next=()=>{setError('');if(step===1&&(!f.full_name||!f.email||!f.phone||!f.city||!f.career_role||!f.company_organisation||!f.industry||!f.years_experience||!f.functional_area)){setError('Please complete all required fields.');return}if(step===2&&(!f.ai_experience_level||!f.mvp_preferences.length)){setError('Choose your AI experience level and at least one MVP.');return}setStep(s=>Math.min(3,s+1));window.scrollTo(0,0)};
 const submit=async()=>{if(!f.consent){setError('Please confirm consent before submitting.');return}setBusy(true);setError('');try{const r=await fetch(API+'/submit-attendee-registration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)});const x=await r.json();if(!r.ok)throw new Error(x.error||'Could not submit');setDone(true)}catch(e){setError(e.message)}finally{setBusy(false)}};
 if(done)return <main className="regDone"><div><span>AI LAB</span><h1>You're registered.</h1><p>Thanks, {f.full_name}. Your workshop preferences have been received.</p><a href="/">Return to AI Lab →</a></div></main>;
 return <main className="regShell"><div className="regFrame">
  <aside className="regRail"><a href="/" className="regBrand"><span className="brandMark">A</span><span>AI LAB<small>AI BUSINESS<br/>TRANSFORMATION</small></span></a><h2>From Ideas to<br/>Real Impact</h2><p>A hands-on workshop for CXOs, founders and business leaders.</p><div className="benefits"><div><i>♟</i><span>Build <b>Real AI MVPs</b><small>in two days</small></span></div><div><i>✦</i><span>Learn from<br/>experts & peers</span></div><div><i>⌘</i><span>Expand<br/>your network</span></div><div><i>↗</i><span>Leave with a<br/>90-day action plan</span></div></div><div className="event"><b>▣</b><span>25 – 26 Sep 2026<small>Sofitel BKC, Mumbai</small></span></div><blockquote>“Practical, focused and immediately applicable. A must for business leaders.”<small>— Previous Attendee</small></blockquote><div className="railArt"><img src={ASSET+'attendee-mumbai-skyline.jpg'} alt=""/><strong>Build<br/>What’s Next</strong></div></aside>
  <section className="regMain"><div className="stepCount">Step {step} of 3</div><div className="steps">{['You & Profile','AI & Your Interests','Review & Submit'].map((x,i)=><div className={step>=i+1?'active':''} key={x}><b>{step>i+1?'✓':i+1}</b><span>{x}</span></div>)}</div><div className="regCard">
   {step===1&&<><div className="formHead"><div><small>ATTENDEE REGISTRATION</small><h1>Let’s get to know <em>you.</em></h1><p>Share a few details so we can personalise your workshop experience.</p></div><div className="time">◷ <span>Takes about<br/><b>3 minutes</b></span></div></div><div className="field full"><label>Full Name *</label><div className="inputWrap"><Icon>♙</Icon><input autoComplete="name" value={f.full_name} onChange={e=>set('full_name',e.target.value)} placeholder="Enter your full name"/></div></div><div className="field full"><label>Email Address *</label><div className="inputWrap"><Icon>✉</Icon><input type="email" autoComplete="email" value={f.email} onChange={e=>set('email',e.target.value)} placeholder="name@company.com"/></div></div><div className="two phoneCity"><div className="field"><label>Phone / WhatsApp *</label><div className="phoneWrap"><span className="country">🇮🇳 +91⌄</span><div className="inputWrap"><Icon>⌕</Icon><input type="tel" autoComplete="tel" value={f.phone} onChange={e=>set('phone',e.target.value)} placeholder="98765 43210"/></div></div></div><div className="field"><label>City *</label><div className="inputWrap"><Icon>⌖</Icon><input autoComplete="address-level2" value={f.city} onChange={e=>set('city',e.target.value)} placeholder="Mumbai"/></div></div></div><fieldset><legend>Your Current Role *</legend><div className="roleGrid">{roles.map((x,i)=><button type="button" className={f.career_role===x?'on':''} onClick={()=>set('career_role',x)} key={x}><span>{['◉','◆','▤','♙','◇','◌'][i]}</span>{x}</button>)}</div></fieldset><div className="two"><div className="field"><label>Company / Organisation *</label><div className="inputWrap"><Icon>▥</Icon><input value={f.company_organisation} onChange={e=>set('company_organisation',e.target.value)} placeholder="Enter company name"/></div></div><div className="field"><label>Industry *</label><select value={f.industry} onChange={e=>set('industry',e.target.value)}><option value="">Select industry</option>{['Technology','Financial Services','Professional Services','Retail / Consumer','Healthcare','Manufacturing','Media / Marketing','Education','Real Estate','Other'].map(x=><option key={x}>{x}</option>)}</select></div></div><div className="two"><div className="field"><label>Years of Professional Experience *</label><select value={f.years_experience} onChange={e=>set('years_experience',e.target.value)}><option value="">Select range</option>{['0–2','3–5','6–10','11–15','15+'].map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Primary Functional Area *</label><select value={f.functional_area} onChange={e=>set('functional_area',e.target.value)}><option value="">Select function</option>{['Leadership / Strategy','Sales / Business Development','Marketing','Finance','Operations','HR / People','Technology / Product','Legal / Compliance','Consulting','Other'].map(x=><option key={x}>{x}</option>)}</select></div></div></>}
   {step===2&&<><div className="formHead"><div><small>ATTENDEE REGISTRATION</small><h1>Your AI experience & what you want to <em>build.</em></h1><p>Tell us where you are today and choose up to two MVPs.</p></div><img className="headVisual" src={ASSET+'attendee-wave-light.jpg'} alt="AI technology visual"/></div><fieldset><legend>Your AI Experience Level *</legend><div className="levelGrid">{levels.map(x=><button type="button" className={f.ai_experience_level===x?'on':''} onClick={()=>set('ai_experience_level',x)} key={x}><b>{x}</b></button>)}</div></fieldset><fieldset><legend>Which AI tools have you used?</legend><div className="chips">{tools.map(x=><button type="button" className={f.ai_tools.includes(x)?'on':''} onClick={()=>toggleTool(x)} key={x}>{x}</button>)}</div></fieldset><fieldset><legend>What would you like to build? <small>Select up to 2 — order = preference</small></legend><div className="mvpGrid">{options.map(o=><button type="button" className={f.mvp_preferences.includes(o.slug)?'on':''} onClick={()=>chooseMvp(o.slug)} key={o.slug}><i>{f.mvp_preferences.indexOf(o.slug)+1||''}</i><b>{o.title}</b><span>{o.description}</span></button>)}</div></fieldset>{f.mvp_preferences.includes('something-else')&&<label>What would you like to build?<textarea value={f.other_mvp_idea} onChange={e=>set('other_mvp_idea',e.target.value)} maxLength={300}/></label>}</>}
   {step===3&&<><div className="formHead"><div><small>ATTENDEE REGISTRATION</small><h1>Almost <em>there!</em></h1><p>Review your details and submit your registration.</p></div><img className="headVisual" src={ASSET+'step1-workshop-collaboration.jpg'} alt="AI Lab collaboration"/></div><div className="review"><section><h3>Your Profile <button type="button" onClick={()=>setStep(1)}>Edit</button></h3><b>{f.full_name}</b><p>{f.email} · {f.phone}<br/>{f.city} · {f.career_role}<br/>{f.company_organisation} · {f.industry}<br/>{f.years_experience} years · {f.functional_area}</p></section><section><h3>AI Experience <button type="button" onClick={()=>setStep(2)}>Edit</button></h3><p><b>{f.ai_experience_level}</b><br/>{f.ai_tools.join(', ')||'No tools selected'}</p></section><section><h3>Workshop Interests <button type="button" onClick={()=>setStep(2)}>Edit</button></h3>{f.mvp_preferences.map((s,i)=><p key={s}>Preference {i+1}: <b>{options.find(o=>o.slug===s)?.title||s}</b></p>)}</section></div><label className="consent"><input type="checkbox" checked={f.consent} onChange={e=>set('consent',e.target.checked)}/> I agree to the use of my information for workshop registration, planning and coordination.</label></>}
   {error&&<p className="regError" role="alert">{error}</p>}<div className="regActions"><button type="button" disabled={step===1} onClick={()=>setStep(s=>Math.max(1,s-1))}>← &nbsp; Back</button>{step<3?<button type="button" className="primary" onClick={next}>Save & Continue &nbsp; →</button>:<button type="button" className="primary" disabled={busy} onClick={submit}>{busy?'Submitting…':'Submit Registration →'}</button>}</div><div className="trust"><span className="shield">⬟</span><span><b>Your information is secure</b><small>We only use this information for workshop coordination.</small></span><span className="cloud">♧</span><span><b>Saved on this page</b><small>Until you submit</small></span></div>
  </div><footer className="regFooter"><b><span className="miniMark">A</span> AI LAB<small>An ELIV8 LYF initiative</small></b><nav><a href="#">Privacy</a><a href="#">Terms</a><a href="#">Contact</a></nav></footer></section>
 </div></main>;
}
